# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.cache/wt} [current_project]
set_property parent.project_path {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {{D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/firmware.mem}}
read_verilog -library xil_defaultlib -sv {
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/ALU.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/SignExt.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/controller.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/datapath.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/fir_accelerator_top.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/memorys.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/register_en.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/register_file.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/register_simple.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/uart_rx.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/uart_top.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/uart_tx.sv}
  {D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/new/top.sv}
}
read_ip -quiet {{D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/constrs_1/new/pins.xdc}}
set_property used_in_implementation false [get_files {{D:/Vivado _projects/RISC-V/DSD_Capstone/MultiCycle.srcs/constrs_1/new/pins.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
